/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface HelloWorld {
    'birthyear': any;
    'firstname': any;
    'lastname': any;
    'sayMyName': () => Promise<void>;
  }
}

declare namespace LocalJSX {
  interface HelloWorld extends JSXBase.HTMLAttributes {
    'birthyear'?: any;
    'firstname'?: any;
    'lastname'?: any;
  }

  interface IntrinsicElements {
    'hello-world': HelloWorld;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLHelloWorldElement extends Components.HelloWorld, HTMLStencilElement {}
  var HTMLHelloWorldElement: {
    prototype: HTMLHelloWorldElement;
    new (): HTMLHelloWorldElement;
  };

  interface HTMLElementTagNameMap {
    'hello-world': HTMLHelloWorldElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

